### PR TITLE
fix spaces

### LINKED ISSUE #10: Encoding of space in Issuer
Spaces in the querystring are encoded with a `+`. Google Authenticator interprets this as a literal `+`.

I checked out two examples, and they both use %20: https://github.com/mdp/rotp#generating-qr-codes-for-provisioning-mobile-apps and https://stefansundin.github.io/2fa-qr/

### PR DESCRIPTION
**Pull request by sanderhahn**
Closes #10

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

File: lib/nimble_totp.ex [hunk 1]
```diff
@@ -99,7 +99,7 @@ defmodule NimbleTOTP do
   def otpauth_uri(label, secret, uri_params \\ []) do
     key = Base.encode32(secret, padding: false)
     params = [{:secret, key} | uri_params]
-    query = URI.encode_query(params)
+    query = URI.encode_query(params, :rfc3986)
```
Comment (wojtekmach) [inline lib/nimble_totp.ex:102]: Per https://hexdocs.pm/elixir/URI.html#encode_query/2, `:rfc3986` is only available since Elixir v1.12. We should either bump the Elixir requirement or work around it (with a reminder to remove it once we require Elixir v1.12)

@josevalim should we add workaround or bump requirement?

Comment (wojtekmach) [reply lib/nimble_totp.ex:102]: ah, it was bumping requirement, good call.
